import { StyleSheet } from "@react-pdf/renderer";

export const REPORT_PAGES = 6;

export const colors = {
  navy: "#202356",
  navyDeep: "#181d42",
  gold: "#b2936b",
  ink: "#1a1a1a",
  muted: "#666666",
  rule: "#e8e4dc",
  panel: "#f3f1ec",
  page: "#F8F7F4",
  white: "#ffffff",
};

export const fonts = {
  heading: "Playfair Display",
  body: "Aktiv Grotesk",
};

export const reportStyles = StyleSheet.create({
  page: {
    backgroundColor: colors.page,
    paddingTop: 52,
    paddingBottom: 44,
    paddingHorizontal: 40,
    fontFamily: fonts.body,
    fontSize: 9,
    color: colors.ink,
  },
  coverPage: {
    backgroundColor: colors.navy,
    paddingTop: 0,
    paddingBottom: 44,
    paddingHorizontal: 40,
    fontFamily: fonts.body,
  },
  runningHeader: {
    position: "absolute",
    top: 18,
    left: 40,
    right: 40,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.rule,
    paddingBottom: 6,
  },
  runningHeaderText: {
    fontSize: 6.5,
    color: colors.muted,
    fontFamily: fonts.body,
    fontWeight: 500,
    letterSpacing: 0.3,
  },
  runningFooter: {
    position: "absolute",
    bottom: 16,
    left: 40,
    right: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 0.5,
    borderTopColor: colors.rule,
    paddingTop: 6,
  },
  footerText: {
    fontSize: 6.5,
    color: colors.muted,
    fontFamily: fonts.body,
  },
  footerCenter: {
    fontSize: 6.5,
    color: colors.muted,
    fontFamily: fonts.body,
    fontWeight: 500,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  coverLogo: {
    width: 180,
    height: 32,
    marginBottom: 48,
  },
  coverTitle: {
    fontFamily: fonts.heading,
    fontSize: 28,
    color: colors.white,
    marginBottom: 8,
  },
  coverSubtitle: {
    fontFamily: fonts.body,
    fontSize: 11,
    color: "#d4c4ad",
    marginBottom: 4,
  },
  coverMeta: {
    fontFamily: fonts.body,
    fontSize: 9,
    color: "rgba(255,255,255,0.72)",
    marginTop: 24,
  },
  coverRule: {
    width: 48,
    height: 2,
    backgroundColor: colors.gold,
    marginTop: 20,
    marginBottom: 20,
  },
  level1: {
    fontFamily: fonts.heading,
    fontSize: 22,
    color: colors.navy,
    marginBottom: 4,
  },
  level2: {
    fontFamily: fonts.heading,
    fontSize: 14,
    color: colors.navy,
    marginTop: 4,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 0.75,
    borderBottomColor: colors.gold,
  },
  level3: {
    fontFamily: fonts.body,
    fontSize: 9,
    fontWeight: 600,
    color: colors.navy,
    marginTop: 10,
    marginBottom: 6,
  },
  bodyText: {
    fontFamily: fonts.body,
    fontSize: 9,
    lineHeight: 1.55,
    color: "#444444",
  },
  muted: {
    fontFamily: fonts.body,
    fontSize: 8,
    color: colors.muted,
    lineHeight: 1.45,
  },
  kpiBand: {
    flexDirection: "row",
    backgroundColor: colors.panel,
    borderLeftWidth: 2,
    borderLeftColor: colors.gold,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginTop: 12,
    marginBottom: 14,
    gap: 8,
  },
  kpiCell: {
    flex: 1,
  },
  kpiLabel: {
    fontSize: 6.5,
    fontFamily: fonts.body,
    fontWeight: 500,
    color: colors.muted,
    letterSpacing: 0.9,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  kpiValue: {
    fontSize: 15,
    fontFamily: fonts.body,
    fontWeight: 600,
    color: colors.navy,
  },
  detailGrid: {
    flexDirection: "row",
    gap: 20,
    marginBottom: 12,
  },
  detailCol: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 6.5,
    fontFamily: fonts.body,
    fontWeight: 500,
    color: colors.gold,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  detailValue: {
    fontSize: 9,
    fontFamily: fonts.body,
    color: "#333333",
    marginBottom: 6,
  },
  table: {
    marginBottom: 10,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: colors.navy,
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  tableHeaderText: {
    fontSize: 7,
    fontFamily: fonts.body,
    fontWeight: 500,
    color: colors.white,
    letterSpacing: 0.3,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.rule,
  },
  tableRowAlt: {
    backgroundColor: "rgba(255,255,255,0.55)",
  },
  tableCell: {
    fontSize: 8,
    fontFamily: fonts.body,
    color: "#333333",
  },
  tableCellRight: {
    fontSize: 8,
    fontFamily: fonts.body,
    fontWeight: 600,
    textAlign: "right",
    color: colors.ink,
  },
  tableTotal: {
    flexDirection: "row",
    backgroundColor: colors.panel,
    borderTopWidth: 1,
    borderTopColor: colors.gold,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  tableTotalText: {
    fontSize: 8,
    fontFamily: fonts.body,
    fontWeight: 600,
    color: colors.navy,
  },
  chartBox: {
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderWidth: 0.5,
    borderColor: colors.rule,
    backgroundColor: colors.white,
  },
  chartCaption: {
    fontSize: 7,
    color: colors.muted,
    marginBottom: 4,
    fontFamily: fonts.body,
  },
  chartAxisLabel: {
    fontSize: 6.5,
    color: colors.muted,
    fontFamily: fonts.body,
  },
  footnote: {
    fontSize: 7,
    color: colors.muted,
    marginTop: 4,
    lineHeight: 1.4,
    fontFamily: fonts.body,
    fontStyle: "italic",
  },
  bulletRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 5,
  },
  bulletDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.gold,
    marginTop: 4,
  },
  emptyRow: {
    fontSize: 8,
    color: colors.muted,
    fontFamily: fonts.body,
    paddingVertical: 6,
  },
});
