import { StyleSheet } from "@react-pdf/renderer";

export const REPORT_DOCUMENT_TITLE = "Investment Report";
export const REPORT_COVER_TITLE = "Your Investment Report";

/** Base pages: cover, disclaimer, overview, allocation, transactions, exec, performance x3, back cover */
export const REPORT_BASE_PAGES = 10;

export const FIRM_ADDRESS =
  "WC L, 190 Elgin Avenue, George Town, Grand Cayman, Cayman Islands, KY-1 9008";

export const colors = {
  navy: "#202356",
  navyDeep: "#181d42",
  gold: "#b2936b",
  ink: "#1a1a1a",
  muted: "#666666",
  rule: "#e8e4dc",
  panel: "#f3f1ec",
  page: "#F8F7F4",
  white: "#ffffff",
};

export const fonts = {
  heading: "Playfair Display",
  body: "Playfair Display",
};

export const reportStyles = StyleSheet.create({
  page: {
    backgroundColor: colors.page,
    paddingTop: 52,
    paddingBottom: 56,
    paddingHorizontal: 40,
    fontFamily: fonts.body,
    fontSize: 9,
    color: colors.ink,
  },
  pageLandscape: {
    backgroundColor: colors.page,
    paddingTop: 76,
    paddingBottom: 52,
    paddingHorizontal: 36,
    fontFamily: fonts.body,
    fontSize: 9,
    color: colors.ink,
  },
  coverPage: {
    backgroundColor: colors.navy,
    padding: 0,
    fontFamily: fonts.body,
    flexDirection: "row",
  },
  coverPhoto: {
    width: 400,
    height: 595,
    objectFit: "cover",
  },
  coverPanel: {
    flex: 1,
    backgroundColor: colors.navy,
    paddingLeft: 52,
    paddingRight: 36,
    justifyContent: "center",
    position: "relative",
  },
  backCoverPage: {
    backgroundColor: colors.navy,
    paddingHorizontal: 48,
    fontFamily: fonts.body,
    position: "relative",
  },
  backCoverPattern: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.35,
  },
  backCoverPatternImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  backCoverContent: {
    flex: 1,
    position: "relative",
  },
  backCoverCenter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  backCoverLogo: {
    width: 220,
    height: 40,
    marginBottom: 28,
  },
  backCoverTagline: {
    fontFamily: fonts.body,
    fontSize: 11,
    color: colors.gold,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  backCoverRule: {
    width: 56,
    height: 2,
    backgroundColor: colors.gold,
  },
  backCoverFooter: {
    position: "absolute",
    bottom: 36,
    left: 48,
    right: 48,
    alignItems: "center",
  },
  backCoverFooterText: {
    fontFamily: fonts.body,
    fontSize: 8,
    color: "rgba(255,255,255,0.65)",
    lineHeight: 1.5,
    textAlign: "center",
  },
  pageTitle: {
    fontFamily: fonts.heading,
    fontSize: 20,
    color: colors.navy,
    marginBottom: 14,
  },
  pageTitleLandscape: {
    fontFamily: fonts.heading,
    fontSize: 20,
    color: colors.gold,
    marginBottom: 8,
  },
  pageHeaderRow: {
    position: "absolute",
    top: 22,
    left: 36,
    right: 36,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  pageHeaderMeta: {
    width: 148,
    paddingTop: 6,
    paddingRight: 10,
    gap: 2,
  },
  pageHeaderLine: {
    fontSize: 8,
    color: colors.ink,
    fontFamily: fonts.body,
  },
  pageHeaderLabel: {
    fontFamily: fonts.body,
    fontWeight: 700,
    fontSize: 8,
    color: colors.ink,
  },
  titleRule: {
    borderBottomWidth: 1,
    borderBottomStyle: "dotted",
    borderBottomColor: colors.gold,
    marginTop: 2,
  },
  footerRule: {
    position: "absolute",
    bottom: 40,
    left: 36,
    right: 36,
    borderBottomWidth: 0.6,
    borderBottomColor: "#1a1a1a",
  },
  footerLogo: {
    width: 84,
    height: 15,
  },
  referenceFooter: {
    position: "absolute",
    bottom: 18,
    left: 36,
    right: 36,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  referenceFooterPortrait: {
    position: "absolute",
    bottom: 18,
    left: 40,
    right: 40,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  referenceFooterMeta: {
    gap: 2,
  },
  referenceFooterLine: {
    fontSize: 7,
    color: colors.muted,
    fontFamily: fonts.body,
  },
  referencePageNumber: {
    fontSize: 8,
    color: colors.ink,
    fontFamily: fonts.body,
  },
  coverLogo: {
    position: "absolute",
    right: 32,
    bottom: 28,
    width: 132,
    height: 23,
  },
  coverClientName: {
    fontFamily: fonts.heading,
    fontSize: 28,
    color: colors.gold,
    marginBottom: 18,
  },
  coverTitle: {
    fontFamily: fonts.body,
    fontSize: 13,
    color: colors.white,
    marginBottom: 26,
  },
  coverDate: {
    fontFamily: fonts.body,
    fontSize: 11,
    color: colors.white,
  },
  level1: {
    fontFamily: fonts.heading,
    fontSize: 22,
    color: colors.navy,
    marginBottom: 4,
  },
  level2: {
    fontFamily: fonts.heading,
    fontSize: 14,
    color: colors.navy,
    marginTop: 4,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 0.75,
    borderBottomColor: colors.gold,
  },
  level3: {
    fontFamily: fonts.body,
    fontSize: 9,
    fontWeight: 600,
    color: colors.navy,
    marginTop: 10,
    marginBottom: 6,
  },
  bodyText: {
    fontFamily: fonts.body,
    fontSize: 9,
    lineHeight: 1.55,
    color: "#444444",
  },
  muted: {
    fontFamily: fonts.body,
    fontSize: 8,
    color: colors.muted,
    lineHeight: 1.45,
  },
  kpiBand: {
    flexDirection: "row",
    backgroundColor: colors.panel,
    borderLeftWidth: 2,
    borderLeftColor: colors.gold,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginTop: 12,
    marginBottom: 14,
    gap: 8,
  },
  kpiCell: {
    flex: 1,
  },
  kpiLabel: {
    fontSize: 6.5,
    fontFamily: fonts.body,
    fontWeight: 500,
    color: colors.muted,
    letterSpacing: 0.9,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  kpiValue: {
    fontSize: 15,
    fontFamily: fonts.body,
    fontWeight: 600,
    color: colors.navy,
  },
  detailGrid: {
    flexDirection: "row",
    gap: 20,
    marginBottom: 12,
  },
  detailCol: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 6.5,
    fontFamily: fonts.body,
    fontWeight: 500,
    color: colors.gold,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  detailValue: {
    fontSize: 9,
    fontFamily: fonts.body,
    color: "#333333",
    marginBottom: 6,
  },
  table: {
    marginBottom: 10,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: colors.navy,
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  tableHeaderText: {
    fontSize: 7,
    fontFamily: fonts.body,
    fontWeight: 500,
    color: colors.white,
    letterSpacing: 0.3,
  },
  tableHeaderTextLandscape: {
    fontSize: 7.5,
    fontFamily: fonts.body,
    fontWeight: 500,
    color: colors.white,
    letterSpacing: 0.3,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.rule,
  },
  tableRowAlt: {
    backgroundColor: "rgba(255,255,255,0.55)",
  },
  tableCell: {
    fontSize: 8,
    fontFamily: fonts.body,
    color: "#333333",
  },
  tableCellLandscape: {
    fontSize: 8.5,
    fontFamily: fonts.body,
    color: "#333333",
  },
  tableCellRight: {
    fontSize: 8,
    fontFamily: fonts.body,
    fontWeight: 600,
    textAlign: "right",
    color: colors.ink,
  },
  tableCellRightLandscape: {
    fontSize: 8.5,
    fontFamily: fonts.body,
    fontWeight: 600,
    textAlign: "right",
    color: colors.ink,
  },
  tableTotal: {
    flexDirection: "row",
    backgroundColor: colors.panel,
    borderTopWidth: 1,
    borderTopColor: colors.gold,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  tableTotalText: {
    fontSize: 8,
    fontFamily: fonts.body,
    fontWeight: 600,
    color: colors.navy,
  },
  tableTotalTextLandscape: {
    fontSize: 8.5,
    fontFamily: fonts.body,
    fontWeight: 600,
    color: colors.navy,
  },
  chartBox: {
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderWidth: 0.5,
    borderColor: colors.rule,
    backgroundColor: colors.white,
  },
  chartBoxLandscape: {
    marginTop: 8,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderWidth: 0.5,
    borderColor: colors.rule,
    backgroundColor: colors.white,
    alignItems: "center",
  },
  allocationPage: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 8,
    paddingBottom: 8,
  },
  allocationSplitPage: {
    flexDirection: "row",
    backgroundColor: colors.white,
    padding: 0,
    fontFamily: fonts.body,
  },
  allocationPhoto: {
    width: 400,
    height: 595,
    objectFit: "cover",
  },
  allocationPanel: {
    flex: 1,
    paddingTop: 40,
    paddingHorizontal: 28,
    paddingBottom: 52,
    position: "relative",
  },
  allocationFooterRule: {
    position: "absolute",
    bottom: 40,
    left: 28,
    right: 28,
    borderBottomWidth: 0.6,
    borderBottomColor: "#1a1a1a",
  },
  allocationFooter: {
    position: "absolute",
    bottom: 16,
    left: 28,
    right: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  chartCaption: {
    fontSize: 7,
    color: colors.muted,
    marginBottom: 4,
    fontFamily: fonts.body,
  },
  chartAxisLabel: {
    fontSize: 6.5,
    color: colors.muted,
    fontFamily: fonts.body,
  },
  footnote: {
    fontSize: 7,
    color: colors.muted,
    marginTop: 6,
    lineHeight: 1.4,
    fontFamily: fonts.body,
    fontStyle: "italic",
  },
  bulletRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 5,
  },
  bulletDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.gold,
    marginTop: 4,
  },
  emptyRow: {
    fontSize: 8,
    color: colors.muted,
    fontFamily: fonts.body,
    paddingVertical: 6,
  },
  disclaimerTitle: {
    fontFamily: fonts.body,
    fontSize: 9,
    fontWeight: 600,
    color: colors.ink,
    marginTop: 8,
    marginBottom: 10,
  },
  disclaimerBody: {
    fontFamily: fonts.body,
    fontSize: 8,
    lineHeight: 1.55,
    color: "#444444",
    textAlign: "justify",
  },
});

export function computeReportTotalPages(holdingsPageCount: number): number {
  return REPORT_BASE_PAGES + holdingsPageCount;
}
